FROM python:3.6.0

# COPY requirements.txt /requirements.txt
# COPY requirements-dev.txt /requirements-dev.txt

# RUN pip install --upgrade pip

# RUN pip install -r requirements-dev.txt

ENV repo SOCNET
ENV PYTHONPATH "/home/${repo}:${PYTHONPATH}"

WORKDIR /home/$project/
